color: null
fieldLayouts:
  0ffa6589-9312-457b-9d1e-4ba29ccb413b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-30T20:31:18+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e9da72c0-b220-46f5-b8c3-7a9ada8792ad
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T20:46:35+00:00'
            elementCondition: null
            fieldUid: 8799e074-514f-4b7a-af19-f42b60826eb9 # Featured image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4d31128-de09-416e-a863-e5b1c3e25b0d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T20:46:35+00:00'
            elementCondition: null
            fieldUid: 015c4aa9-1da9-442b-869a-1315bc916a30 # Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 80f4fdaa-54c5-4a1e-91ff-fa8e8a0e80e2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-24T20:46:46+00:00'
            elementCondition: null
            fieldUid: e943d4ec-4cf4-4c3a-89e8-6308943df394 # Types of issues you can help
            handle: null
            includeInCards: false
            instructions: null
            label: 'Issue tags'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8085fde5-da70-4880-bf25-83f99d392c67
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T20:47:49+00:00'
            elementCondition: null
            fieldUid: adccc74b-e492-4515-903f-798f62bb0256 # Body
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e87a7e20-a992-44b7-9670-0a3dcdba9dd0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a8b7f5b2-bce1-4eae-b56a-7475d659bc61
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-30T20:46:35+00:00'
            elementCondition: null
            fieldUid: 43f6ee32-dbe7-405f-ba2a-3fbe8b2dd0ae # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e850c1b-7240-4066-ba15-a350dc30ce9a
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 4302d7b0-98a3-4e71-9675-103ce65e22fb
        userCondition: null
handle: article
hasTitleField: true
icon: null
name: Article
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
