color: null
description: null
fieldLayouts:
  08cb27c0-8c4b-46cc-bd0c-e46ff0df6811:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-12T20:41:12+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9897d3ef-0e9d-470d-98e7-36cb4c3083c3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-12T20:40:15+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4469bf0d-c096-401e-bff6-e93ec73701c0 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33d94521-dff5-447a-9d0e-5739e60f5448
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-12T21:27:47+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8742d0e0-5abb-4774-b8a6-05a5668e9098 # Short summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d1c3cf2-554d-4075-b6f6-8f32c09722ff
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 697d73bb-609d-4c98-8cee-4f2f8a9cdd02
        userCondition: null
handle: imagecard
hasTitleField: true
icon: null
name: _imagecard
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
