defaultPlacement: end
fieldLayouts:
  eec9dff1-5e86-4606-9a6c-3eb76ea122bf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-05T14:59:37+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 0f11ab38-b18c-45cf-9012-eb31b4ab0c83
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-06T13:48:57+00:00'
            elementCondition: null
            fieldUid: 12f0e524-edea-401a-a140-70061e2a4795 # Icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62ae7c0a-ed93-4688-adf7-a5968c04e083
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-06T13:49:03+00:00'
            elementCondition: null
            fieldUid: e9b55431-481c-480d-9cc8-ea4734a67d0e # Category description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7534759a-9e53-4e74-ad16-6e0c7e5c5422
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3338fff8-bba5-43b1-b7fd-15c1759ca1b8
        userCondition: null
handle: issues
name: Issues
siteSettings:
  c0ed5fcd-bf5e-4d52-9094-794f737b4080: # Brighton & Hove Therapy Space
    hasUrls: true
    template: content/category-list.twig
    uriFormat: 'issues/{slug}'
structure:
  maxLevels: 1
  uid: a4b4a097-f8d7-4d16-ac4f-1af180b60f13
