altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  a20806c1-cf7a-4de1-a8b5-e32bee464836:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-29T16:47:17+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 9f2ce5ea-409e-4f8e-93ba-523028a04f74
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d654ae57-fcde-4b0b-a1b0-a34f2c615b02
        userCondition: null
fs: tempFiles
handle: tempFiles
name: 'Temp files'
sortOrder: 4
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
