altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  a25ff9db-3d63-4d86-96d8-9805de8c329b:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-09T11:01:55+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 155921b4-cf58-4211-9ac2-47861df9ad5e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a9694496-fe36-4543-9480-416993d286cf
        userCondition: null
fs: docs
handle: therapistDocs
name: 'Therapist docs'
sortOrder: 7
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
