altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  b260e1a4-a3d4-4721-a6d4-be8e0d5fb323:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-29T10:50:49+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: cd62d8d7-68ca-4892-b842-4d0f250eba98
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f27a0f60-2122-42d5-a3a9-63ee8dbb2dfd
        userCondition: null
fs: userphotos
handle: userphotos
name: 'User photos'
sortOrder: 1
subpath: userphotos
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: userphototransforms
