columnSuffix: null
handle: contactPreference
instructions: 'How would you like to be contacted?'
name: 'Contact preference'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - 'By phone'
        -
          - value
          - phone
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'By email'
        -
          - value
          - email
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
