columnSuffix: null
handle: sessionRate
instructions: 'Use this field to put your usual session rate'
name: 'Session rate'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: £
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: 'per session'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
