dateModified: 1757881379
elementSources:
  craft\elements\Entry:
    -
      key: '*'
      type: native
    -
      defaultSort:
        - title
        - asc
      defaultViewMode: ''
      disabled: false
      key: singles
      tableAttributes:
        - status
        - link
      type: native
    -
      heading: Channels
      key: 'heading:4525a7c6-879e-400e-99c4-59619943a001'
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:99287739-b68e-4cec-b31c-9f8b612d8fa6' # Articles
      tableAttributes:
        - status
        - 'field:8799e074-514f-4b7a-af19-f42b60826eb9' # Featured image
        - postDate
        - authors
        - link
      type: native
    -
      heading: Structures
      key: 'heading:e95996d2-7244-4803-a66f-d428feae6edc'
      type: heading
    -
      key: 'section:90155b7e-865d-4cb6-a76b-76906dedad56' # Type of Issues
      type: native
    -
      key: 'section:49141ff0-5149-43b7-91d1-5c8d09a915ed' # Types of Therapy
      type: native
    -
      heading: 'Other content'
      key: 'heading:41cf3515-8fb8-4263-bce3-a58512febef4'
      type: heading
    -
      key: 'section:17f66194-2bba-4d08-a705-9823e9054f86' # Pages
      type: native
    -
      heading: ''
      key: 'heading:0e7b0758-8c3a-4476-ac5a-744d7285d59d'
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:e6ff9992-97aa-4cd6-b9ea-5743266547cb' # Enquiries
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - authors
        - link
        - 'field:f11c0ca4-477e-4f64-b73d-97084f9d6a56' # Email
      type: native
    -
      key: 'section:9fb734e9-d00d-4847-a7cf-894e3d7d4bb1' # Menu
      type: native
  craft\elements\User:
    -
      defaultSort:
        - email
        - asc
      disabled: false
      key: '*'
      tableAttributes:
        - id
        - status
        - fullName
        - email
        - dateCreated
        - lastLoginDate
      type: native
    -
      key: admins
      type: native
    -
      heading: 'Account Type'
      type: heading
    -
      key: credentialed
      type: native
    -
      key: inactive
      type: native
    -
      heading: Groups
      type: heading
    -
      defaultSort:
        - email
        - asc
      disabled: false
      key: 'group:b49c197d-26ab-4194-bf60-959a99761cb0' # Counsellors
      tableAttributes:
        - status
        - fullName
        - email
        - dateCreated
        - lastLoginDate
        - id
      type: native
email:
  fromEmail: admin@brightoncounsellingrooms.co.uk
  fromName: 'Brighton Counselling Rooms'
  replyToEmail: admin@brightoncounsellingrooms.co.uk
  template: ''
  transportSettings:
    command: '/usr/sbin/sendmail -bs'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  generalImages:
    hasUrls: true
    name: 'General images'
    settings:
      path: $ASSET_BASE_PATH
    type: craft\fs\Local
    url: $ASSET_BASE_URL
  icons:
    hasUrls: true
    name: Icons
    settings:
      path: $ASSET_BASE_PATH
    type: craft\fs\Local
    url: $ASSET_BASE_URL
  landingImages:
    hasUrls: true
    name: 'Landing images'
    settings:
      path: $ASSET_BASE_PATH
    type: craft\fs\Local
    url: $ASSET_BASE_URL
  tempFiles:
    hasUrls: false
    name: 'Temp files'
    settings:
      path: $ASSET_TMP_PATH
    type: craft\fs\Local
    url: null
  userInsurance:
    hasUrls: true
    name: 'User insurance'
    settings:
      path: $ASSET_BASE_PATH
    type: craft\fs\Local
    url: $ASSET_BASE_URL
  userMembershipLogos:
    hasUrls: true
    name: 'User membership logos'
    settings:
      path: $ASSET_BASE_PATH
    type: craft\fs\Local
    url: $ASSET_BASE_URL
  userphotos:
    hasUrls: true
    name: 'User photos'
    settings:
      path: $ASSET_BASE_PATH
    type: craft\fs\Local
    url: $ASSET_BASE_URL
graphql:
  publicToken:
    enabled: false
    expiryDate: null
meta:
  __names__:
    00af8fd6-bd3f-4722-ab33-7605a9d54295: Rooms # Rooms
    0d2c9898-3ec4-4a84-a6c2-012d385c7fa3: 'Practice description' # Practice description
    2e0f8be2-a26a-4d3b-833e-b9edc93188aa: Pages # Pages
    3a0c7965-1bd5-481a-a6dc-4aae3c19067f: therapist # therapist
    4e3d68f6-f7e1-4f09-befe-49a5dbaff6a6: Concessions # Concessions
    5ba00d2b-52da-4b64-b6e1-64c24d426c19: 'Type of client' # Type of client
    5d532788-0cc7-48de-9b9b-627e7923b222: 'Contact preference' # Contact preference
    6aff28e4-a015-4972-b136-5efb6d158b90: 'sHero background' # sHero background
    7b2532c7-d315-4039-9398-2bdf9550067b: home # home
    8f52ea5a-d933-4740-bc02-d0e5ec935219: 'Temp files' # Temp files
    9ed8b498-6f7f-41dd-a83c-a233d3673db1: 'Site settings' # Site settings
    9fb734e9-d00d-4847-a7cf-894e3d7d4bb1: Menu # Menu
    9fe836ef-ed2f-4a2d-afae-4db9c920e3c6: 'Author Url' # Author Url
    12f0e524-edea-401a-a140-70061e2a4795: Icon # Icon
    015c4aa9-1da9-442b-869a-1315bc916a30: Intro # Intro
    17f66194-2bba-4d08-a705-9823e9054f86: Pages # Pages
    22acdfae-ec39-4281-ba0d-dc432a5cf4da: Issues # Issues
    36dc80ef-c566-4b45-a3fa-53319d7ab7ba: 'Member organisation' # Member organisation
    39db330b-457a-4938-8ab1-b93536a6aa9b: Simple # Simple
    43f6ee32-dbe7-405f-ba2a-3fbe8b2dd0ae: SEO # SEO
    45f99bef-ed2c-476b-a382-35d04507ba5e: Icons # Icons
    48e5cd5f-156a-4a9b-9323-1139b7dda01f: 'Phone number' # Phone number
    49a16490-f1a4-45d4-8189-dda278265b5a: 'Title role' # Title role
    84d3be0c-c468-4664-914c-b80e544b5114: Category # Category
    85d7f167-b012-4f56-9d61-9157c12fc036: 'Insurance proof' # Insurance proof
    92bed5f0-da6f-4abc-8a49-47690cf6b3b7: Therapists # Therapists
    156ff3cf-4dae-4881-87f1-ee5e4dee68c1: 'Profile small' # Profile small
    319c85fe-482c-4f11-aa21-cb3849b718d3: Credit # Credit
    374a5750-6957-4022-9d77-07e164a153b1: 'About me' # About me
    520a0e55-accd-41b4-addc-97ed1155aa67: Card # Card
    835ade6f-a0d3-4cc0-86e6-c979a28f4521: 'Profile medium' # Profile medium
    4469bf0d-c096-401e-bff6-e93ec73701c0: Image # Image
    6229b346-6ed9-4ba1-b01e-d4aa42b7fd07: 'User photos' # User photos
    6703c440-9d6a-4259-a664-20a49d1de297: 'Booking status' # Booking status
    8742d0e0-5abb-4774-b8a6-05a5668e9098: 'Short summary' # Short summary
    8799e074-514f-4b7a-af19-f42b60826eb9: 'Featured image' # Featured image
    13311efd-c22d-440c-9713-216f3cf5e4bd: Availability # Availability
    49141ff0-5149-43b7-91d1-5c8d09a915ed: 'Types of Therapy' # Types of Therapy
    90155b7e-865d-4cb6-a76b-76906dedad56: 'Type of Issues' # Type of Issues
    69499203-0a34-4039-9403-fe134f138cec: _imagecard # _imagecard
    93100866-2fab-487e-8a7b-11e1e16279f3: 'Custom url' # Custom url
    99287739-b68e-4cec-b31c-9f8b612d8fa6: Articles # Articles
    a01fdd0f-90f7-4242-8e96-f7ea7db5e752: 'Verified membership' # Verified membership
    a7da37e8-4e55-4596-b38a-edd9266963a5: 'Session rate' # Session rate
    a1736c2d-efe2-4d60-a66c-6834c06ef483: 'User membership logos' # User membership logos
    a8055963-f807-47a4-9d1c-438e42b5aed3: Images # Images
    adccc74b-e492-4515-903f-798f62bb0256: Body # Body
    ae52dbda-1496-43d4-a8e1-c9d0c45c41f0: 'Membership org id' # Membership org id
    ae114463-f12c-454b-99e4-8f356f97759e: Qualifications # Qualifications
    aea81fe7-465e-41aa-9b2c-04e6578b3c4b: Article # Article
    b49c197d-26ab-4194-bf60-959a99761cb0: Counsellors # Counsellors
    b6914cb8-a88f-4607-a3ca-a82a45a4b9a0: Enquiry # Enquiry
    bac0bf30-6584-41dd-b3ee-64d683d2e1c5: 'Booking enquiries' # Booking enquiries
    c0ed5fcd-bf5e-4d52-9094-794f737b4080: 'Brighton Counselling Rooms' # Brighton Counselling Rooms
    c8e19182-bf6c-49f8-9aa6-9c9fd87ea0d6: Issue # Issue
    c53fedbd-f0cc-4695-b607-17403adb9be9: 'Types of therapy you offer' # Types of therapy you offer
    cba221ca-cce1-410c-a060-923d5b9bcb90: 'Type of therapy' # Type of therapy
    d0511a46-015b-4858-b016-9a9af57d2f74: 'Brighton Counselling Rooms' # Brighton Counselling Rooms
    dad3c1ec-eae2-4bd5-9588-7f07928ebc53: 'Entry link' # Entry link
    db0321e8-dc19-4846-bca2-27ade2d6430e: cta # cta
    e5d33c8a-f8ba-41cc-a093-889571ae2fa5: 'Profile complete' # Profile complete
    e6ff9992-97aa-4cd6-b9ea-5743266547cb: Enquiries # Enquiries
    e9b55431-481c-480d-9cc8-ea4734a67d0e: 'Category description' # Category description
    e39ad651-432c-40e1-9140-c9cfeda98e60: Hide # Hide
    e63d9cc6-ddc5-4c7e-91a3-2ebc12e2cb1d: 'Therapist ID' # Therapist ID
    e943d4ec-4cf4-4c3a-89e8-6308943df394: 'Types of issues you can help' # Types of issues you can help
    e19118e6-96fb-4dc3-b422-7eaa46f16d1e: 'Training & experience' # Training & experience
    edd49f4f-4759-43d3-9247-25bcbcf399d9: Menu # Menu
    f1d9dde5-deed-4482-972c-eb6e5179873d: Home # Home
    f4e6a838-c1ce-4c50-b340-6883d40eeec4: Blur # Blur
    f11c0ca4-477e-4f64-b73d-97084f9d6a56: Email # Email
    f738e4ee-a559-4e36-8c9a-a559088a75af: 'User insurance' # User insurance
    ff3984e1-295c-4571-b408-3a61e0ff8727: 'Card image' # Card image
plugins:
  blur-hash:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  codefield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  convergine-contentbuddy:
    edition: standard
    enabled: true
    licenseKey: EHVKNAU2HJPARGVNA0ZGE81I
    schemaVersion: 1.2.9
    settings:
      apiToken: $OPENAI_API_KEY
      enabledFields:
        __assoc__:
          -
            - title
            - '1'
          -
            - aboutMe
            - '1'
          -
            - body
            - '1'
          -
            - intro
            - '1'
          -
            - phoneNumber
            - ''
          -
            - practiceDescription
            - '1'
          -
            - qualifications
            - ''
          -
            - trainingQualificationsExperience
            - '1'
      frequencyPenalty: 0.0
      generateImageAssetId: 5e570744-2e2c-4726-9c28-43c151acf227
      generateImageFromText: true
      imageModel: openai
      imageSize: 1024x1024
      imagesStyles: natural
      maxTokens: 256
      preferredModel: gpt-4o
      presencePenalty: 0.0
      stabilityAPIKey: ''
      stabilityEngine: stable-diffusion-512-v2-1
      stabilitySampler: DDIM
      stabilityScale: 7
      stabilitySteps: 50
      stabilityStyle: enhance
      systemMessage: ''
      temperature: 0.7
      usePageLang: true
  convergine-pexels:
    edition: standard
    enabled: true
    licenseKey: JU6S3J56528UY7O3JWNSAHRC
    schemaVersion: 1.0.0
    settings:
      apiKey: CfhRYSzrLCWV9GQEbNNNGAf91qTHnmk7lAoDgC5nSQ4uPdmg6hUOa6Z6
      langLocale: en-US
      picsPerPage: '15'
      uploadLocation: 'volumeId:a8055963-f807-47a4-9d1c-438e42b5aed3' # Images
  easy-image:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  element-api:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 5.1.1
  guest-entries:
    edition: standard
    enabled: true
    schemaVersion: 2.1.0
    settings:
      enableCsrfProtection: '1'
      entryVariable: entry
      sections:
        __assoc__:
          -
            - e6ff9992-97aa-4cd6-b9ea-5743266547cb # Enquiries
            -
              __assoc__:
                -
                  - sectionUid
                  - e6ff9992-97aa-4cd6-b9ea-5743266547cb # Enquiries
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - ''
                -
                  - authorUid
                  - bde7d644-9335-4a1c-9d8b-4cadbaf0696b
          -
            - bac0bf30-6584-41dd-b3ee-64d683d2e1c5 # Booking enquiries
            -
              __assoc__:
                -
                  - sectionUid
                  - bac0bf30-6584-41dd-b3ee-64d683d2e1c5 # Booking enquiries
                -
                  - allowGuestSubmissions
                  - '1'
                -
                  - enabledByDefault
                  - '1'
                -
                  - runValidation
                  - ''
                -
                  - authorUid
                  - bde7d644-9335-4a1c-9d8b-4cadbaf0696b
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  postmark:
    edition: standard
    enabled: true
    schemaVersion: 2.0.1
  seomatic:
    edition: standard
    enabled: true
    licenseKey: GQSGB9GRKKMTHKGRREBK6TWM
    schemaVersion: 3.0.13
  splash:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
    settings:
      authorField: credit
      authorUrlField: authorUrl
      colorField: null
      volume: 3
  splashing-images:
    edition: standard
    enabled: true
    schemaVersion: 1.2.0
    settings:
      destination: images
      folder: unsplash
      pluginLabel: Unsplash
  wordsmith:
    edition: standard
    enabled: true
    schemaVersion: 0.0.0.0
system:
  edition: pro
  live: true
  name: 'Brighton Counselling Directory'
  retryDuration: null
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
