defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: b6914cb8-a88f-4607-a3ca-a82a45a4b9a0 # Enquiry
handle: bookingEnquiries
maxAuthors: 1
minAuthors: 1
name: 'Booking enquiries'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  c0ed5fcd-bf5e-4d52-9094-794f737b4080: # Brighton & Hove Therapy Space
    enabledByDefault: true
    hasUrls: true
    template: booking-enquiries/_entry.twig
    uriFormat: 'booking-enquiries/{slug}'
type: channel
