defaultPlacement: end
enableVersioning: true
entryTypes:
  - f1d9dde5-deed-4482-972c-eb6e5179873d # Home
handle: home
maxAuthors: 1
name: home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  c0ed5fcd-bf5e-4d52-9094-794f737b4080: # Brighton Counselling Rooms
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
