defaultPlacement: end
enableVersioning: true
entryTypes:
  - c8e19182-bf6c-49f8-9aa6-9c9fd87ea0d6 # Issue
handle: issues
maxAuthors: 1
name: 'Type of Issues'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  c0ed5fcd-bf5e-4d52-9094-794f737b4080: # Brighton Counselling Rooms
    enabledByDefault: true
    hasUrls: true
    template: content/category-entry.twig
    uriFormat: '{% if object.level == 1 %}issues/{category.inReverse().one().uri}/{slug}{% else %}issues/{parent.uri}/{slug}{% endif %}'
structure:
  maxLevels: null
  uid: b4ca42ef-a5be-4381-953e-1c59be63082d
type: structure
