defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 2e0f8be2-a26a-4d3b-833e-b9edc93188aa # Pages
  -
    uid: 00af8fd6-bd3f-4722-ab33-7605a9d54295 # Rooms
  -
    uid: db0321e8-dc19-4846-bca2-27ade2d6430e # cta
handle: pages
maxAuthors: 1
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c0ed5fcd-bf5e-4d52-9094-794f737b4080: # Brighton Counselling Rooms
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry.twig
    uriFormat: '{% if object.level == 1 %}{slug}{% else %}{parent.uri}/{slug}{% endif %}'
structure:
  maxLevels: null
  uid: 747d0179-a688-4fd4-8643-c670e7fd5319
type: structure
